Formula1/Controllers/RaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Formula1.Data;
using Formula1.Models;

namespace Formula1.Controllers
{
    public class RaceController : Controller
    {
        private readonly Formula1Context _context;

        public RaceController(Formula1Context context)
        {
            _context = context;
        }

        // GET: Race
        public async Task<IActionResult> Index()
        {
            if (!(HttpContext.Session.GetString("IsLoggedIn") == "true"))
            {
                return RedirectToAction("Account", "Login");
            }
            return _context.RaceModel != null ?
                          View(await _context.RaceModel.ToListAsync()) :
                          Problem("Entity set 'Formula1Context.RaceModel'  is null.");
        }

        // public async Task<IActionResult> RaceResults(){
        //     var races = await _context.RaceModel.ToListAsync();

        //     var names = new List<string>();

        //     foreach (var race in races){
        //         names.Add(race.Name);
        //     }

        // }

        public async Task<IActionResult> RaceResult(int? id)
        {
            var raceName = await _context.RaceModel
                .FirstOrDefaultAsync(m => m.RaceId == id);

            ViewBag.RaceName = raceName.Name;

            var raceResults = await _context.RaceResultsModel
                .Where(m => m.Race.RaceId == id)
                .ToListAsync();

            ViewBag.raceResult = raceResults;

            Dictionary<string, int> DriversName = new Dictionary<string, int>();

            var drivers = await _context.DriverModel.ToListAsync();
            var names = new List<string>();

            foreach (var driver in drivers)
            {
                names.Add(driver.FirstName + " " + driver.LastName);
            }

            Dictionary<string, int> DriversNamesID = new Dictionary<string, int>();

            foreach (var driver in drivers)
            {
                DriversNamesID.Add(driver.FirstName + " " + driver.LastName, driver.DriverId);
            }

            ViewBag.DriversNamesID = DriversNamesID;


            return View("RaceResult");
        }

        // GET: Race/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (!(HttpContext.Session.GetString("IsLoggedIn") == "true"))
            {
                return RedirectToAction("Account", "Login");
            }
            if (id == null || _context.RaceModel == null)
            {
                return NotFound();
            }

            var raceModel = await _context.RaceModel
                .FirstOrDefaultAsync(m => m.RaceId == id);
            if (raceModel == null)
            {
                return NotFound();
            }

            return View(raceModel);
        }

        // GET: Race/Create
        public IActionResult Create()
        {
            if (!(HttpContext.Session.GetString("IsLoggedIn") == "true"))
            {
                return RedirectToAction("Account", "Login");
            }
            return View();
        }

        // POST: Race/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RaceId,Year,Round,Name,Date,Url")] RaceModel raceModel)
        {
            if (!(HttpContext.Session.GetString("IsLoggedIn") == "true"))
            {
                return RedirectToAction("Account", "Login");
            }
            if (ModelState.IsValid)
            {
                _context.Add(raceModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(raceModel);
        }

        // GET: Race/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (!(HttpContext.Session.GetString("IsLoggedIn") == "true"))
            {
                return RedirectToAction("Account", "Login");
            }
            if (id == null || _context.RaceModel == null)
            {
                return NotFound();
            }

            var raceModel = await _context.RaceModel.FindAsync(id);
            if (raceModel == null)
            {
                return NotFound();
            }
            return View(raceModel);
        }

        // POST: Race/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RaceId,Year,Round,Name,Date,Url")] RaceModel raceModel)
        {
            if (!(HttpContext.Session.GetString("IsLoggedIn") == "true"))
            {
                return RedirectToAction("Account", "Login");
            }
            if (id != raceModel.RaceId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(raceModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RaceModelExists(raceModel.RaceId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(raceModel);
        }

        // GET: Race/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (!(HttpContext.Session.GetString("IsLoggedIn") == "true"))
            {
                return RedirectToAction("Account", "Login");
            }
            if (id == null || _context.RaceModel == null)
            {
                return NotFound();
            }

            var raceModel = await _context.RaceModel
                .FirstOrDefaultAsync(m => m.RaceId == id);
            if (raceModel == null)
            {
                return NotFound();
            }

            return View(raceModel);
        }

        // POST: Race/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (!(HttpContext.Session.GetString("IsLoggedIn") == "true"))
            {
                return RedirectToAction("Account", "Login");
            }
            if (_context.RaceModel == null)
            {
                return Problem("Entity set 'Formula1Context.RaceModel'  is null.");
            }
            var raceModel = await _context.RaceModel.FindAsync(id);
            if (raceModel != null)
            {
                _context.RaceModel.Remove(raceModel);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RaceModelExists(int id)
        {
            return (_context.RaceModel?.Any(e => e.RaceId == id)).GetValueOrDefault();
        }
    }
}

Formula1/Controllers/RaceResultsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Formula1.Data;
using Formula1.Models;

namespace Formula1.Controllers
{
    public class RaceResultsController : Controller
    {
        private readonly Formula1Context _context;

        public RaceResultsController(Formula1Context context)
        {
            _context = context;
        }

        // GET: RaceResults
        public async Task<IActionResult> Index()
        {
            if (!(HttpContext.Session.GetString("IsLoggedIn") == "true"))
            {
                return RedirectToAction("Account", "Login");
            }
            return _context.RaceResultsModel != null ?
                        View(await _context.RaceResultsModel.ToListAsync()) :
                        Problem("Entity set 'Formula1Context.RaceResultsModel'  is null.");
        }

        // GET: RaceResults/
        public async Task<IActionResult> Race(int? raceId)
        {
            if (!(HttpContext.Session.GetString("IsLoggedIn") == "true"))
            {
                return RedirectToAction("Account", "Login");
            }
            return _context.RaceResultsModel != null ?
                        View(await _context.RaceResultsModel.Where(m => m.Race.RaceId == raceId).ToListAsync()) :
                        Problem("Entity set 'Formula1Context.RaceResultsModel'  is null.");
        }


        // GET: RaceResults/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (!(HttpContext.Session.GetString("IsLoggedIn") == "true"))
            {
                return RedirectToAction("Account", "Login");
            }
            if (id == null || _context.RaceResultsModel == null)
            {
                return NotFound();
            }

            var raceResultsModel = await _context.RaceResultsModel
                .FirstOrDefaultAsync(m => m.ResultId == id);
            if (raceResultsModel == null)
            {
                return NotFound();
            }

            return View(raceResultsModel);
        }

        // GET: RaceResults/Create
        public IActionResult Create()
        {
            if (!(HttpContext.Session.GetString("IsLoggedIn") == "true"))
            {
                return RedirectToAction("Account", "Login");
            }
            return View();
        }

        // POST: RaceResults/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ResultId,Position,StartingGrid,Laps,Time,Points,Sprint,SetFastestLap,FastestLapTime")] RaceResultsModel raceResultsModel)
        {
            if (!(HttpContext.Session.GetString("IsLoggedIn") == "true"))
            {
                return RedirectToAction("Account", "Login");
            }
            if (ModelState.IsValid)
            {
                _context.Add(raceResultsModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(raceResultsModel);
        }

        // GET: RaceResults/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (!(HttpContext.Session.GetString("IsLoggedIn") == "true"))
            {
                return RedirectToAction("Account", "Login");
            }
            if (id == null || _context.RaceResultsModel == null)
            {
                return NotFound();
            }

            var raceResultsModel = await _context.RaceResultsModel.FindAsync(id);
            if (raceResultsModel == null)
            {
                return NotFound();
            }
            return View(raceResultsModel);
        }

        // POST: RaceResults/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ResultId,Position,StartingGrid,Laps,Time,Points,Sprint,SetFastestLap,FastestLapTime")] RaceResultsModel raceResultsModel)
        {
            if (!(HttpContext.Session.GetString("IsLoggedIn") == "true"))
            {
                return RedirectToAction("Account", "Login");
            }
            if (id != raceResultsModel.ResultId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(raceResultsModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RaceResultsModelExists(raceResultsModel.ResultId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(raceResultsModel);
        }

        // GET: RaceResults/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (!(HttpContext.Session.GetString("IsLoggedIn") == "true"))
            {
                return RedirectToAction("Account", "Login");
            }
            if (id == null || _context.RaceResultsModel == null)
            {
                return NotFound();
            }

            var raceResultsModel = await _context.RaceResultsModel
                .FirstOrDefaultAsync(m => m.ResultId == id);
            if (raceResultsModel == null)
            {
                return NotFound();
            }

            return View(raceResultsModel);
        }

        // POST: RaceResults/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (!(HttpContext.Session.GetString("IsLoggedIn") == "true"))
            {
                return RedirectToAction("Account", "Login");
            }
            if (_context.RaceResultsModel == null)
            {
                return Problem("Entity set 'Formula1Context.RaceResultsModel'  is null.");
            }
            var raceResultsModel = await _context.RaceResultsModel.FindAsync(id);
            if (raceResultsModel != null)
            {
                _context.RaceResultsModel.Remove(raceResultsModel);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RaceResultsModelExists(int id)
        {
            return (_context.RaceResultsModel?.Any(e => e.ResultId == id)).GetValueOrDefault();
        }
    }
}

Formula1/Views/Race/Create.cshtml
@model Formula1.Models.RaceModel

@{
    ViewData["Title"] = "Create";
}

<h1>Add Race</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Round" class="control-label"></label>
                <input asp-for="Round" class="form-control" />
                <span asp-validation-for="Round" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Url" class="control-label"></label>
                <input asp-for="Url" class="form-control" />
                <span asp-validation-for="Url" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Formula1/Views/Race/Delete.cshtml
@model Formula1.Models.RaceModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>RaceModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Round)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Round)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Url)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Url)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="RaceId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Formula1/Views/Race/Details.cshtml
@model Formula1.Models.RaceModel

@{
    ViewData["Title"] = "Details";
}

<h1>@Html.DisplayFor(model => model.Name)</h1>

<div>
    <h4>Race</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Round)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Round)
        </dd>
        @* <dt class = "col-sm-2">
        @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
        @Html.DisplayFor(model => model.Name)
        </dd> *@
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Url)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Url)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.RaceId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Formula1/Views/Race/Edit.cshtml
@model Formula1.Models.RaceModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>RaceModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="RaceId" />
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Round" class="control-label"></label>
                <input asp-for="Round" class="form-control" />
                <span asp-validation-for="Round" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Url" class="control-label"></label>
                <input asp-for="Url" class="form-control" />
                <span asp-validation-for="Url" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Formula1/Views/Race/Index.cshtml
@model IEnumerable<Formula1.Models.RaceModel>

@{
    ViewData["Title"] = "Index";
}

<h1 class="standings-header">Races</h1>

<div class="standings">
    <div class="standings-buttons"> 
        <a asp-controller="Race" asp-action="Create" class="btn btn-primary btn-lg">Add Race</a>
    </div>
</div>
<table class="table">
    <thead>
        <tr>
            @* <th>
            @Html.DisplayNameFor(model => model.Year)
            </th> *@
            <th>
                @Html.DisplayNameFor(model => model.Round)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Url)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                @* <td>
            @Html.DisplayFor(modelItem => item.Year)
            </td> *@
                <td>
                    @Html.DisplayFor(modelItem => item.Round)
                </td>
                <td>
                    <a asp-action="RaceResult" asp-route-id="@item.RaceId">
                        @Html.DisplayFor(modelItem => item.Name)
                    </a>    
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Url)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.RaceId">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.RaceId">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.RaceId">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Formula1/Views/Race/RaceResult.cshtml
<h1 class="standings-header">@ViewBag.RaceName Results</h1>

<table class="table">
   <thead>
        <tr>    
            <th> Driver </th>
            <th> Position </th>
            <th> Starting Grid </th>
            <th> Laps </th>
            <th> Time </th>
            <th> Points </th>
            
            <th> Sprint </th>
            
            <th> Set Fastest Lap </th>
            <th> Fastest Lap Time </th>
        </tr>
   </thead>
    <tbody>
        @foreach (var item in ViewBag.raceResult)
        {
            <tr>
                @* <td>
            @item.Driver.Name
            </td> *@
                <td>
                    @foreach (var driver in ViewBag.DriversNamesID){
                        if (driver.Value == item.Driver.DriverId)
                        {
                            @driver.Key
                        }
                    }
                <td>
                    @item.Position
                </td>
                <td>
                    @item.StartingGrid
                </td>
                <td>
                    @item.Laps
                </td>
                <td>
                    @item.Time
                </td>
                <td>
                    @item.Points
                </td>
                <td>
                    @item.Sprint
                </td>
                <td>
                    @item.SetFastestLap
                </td>
                <td>
                    @item.FastestLapTime
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.ResultId" asp-controller="RaceResults">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.ResultId" asp-controller="RaceResults">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.ResultId" asp-controller="RaceResults">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>