Formula1/Controllers/RaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Formula1.Data;
using Formula1.Models;

namespace Formula1.Controllers
{
    public class RaceController : Controller
    {
        private readonly Formula1Context _context;

        public RaceController(Formula1Context context)
        {
            _context = context;
        }

        // GET: Race
        public async Task<IActionResult> Index()
        {
            if (!(HttpContext.Session.GetString("IsLoggedIn") == "true"))
            {
                return RedirectToAction("Account", "Login");
            }
            return _context.RaceModel != null ?
                          View(await _context.RaceModel.ToListAsync()) :
                          Problem("Entity set 'Formula1Context.RaceModel'  is null.");
        }

        // public async Task<IActionResult> RaceResults(){
        //     var races = await _context.RaceModel.ToListAsync();

        //     var names = new List<string>();

        //     foreach (var race in races){
        //         names.Add(race.Name);
        //     }

        // }

        public async Task<IActionResult> RaceResult(int? id)
        {
            var raceName = await _context.RaceModel
                .FirstOrDefaultAsync(m => m.RaceId == id);

            ViewBag.RaceName = raceName.Name;

            var raceResults = await _context.RaceResultsModel
                .Where(m => m.Race.RaceId == id)
                .ToListAsync();

            ViewBag.raceResult = raceResults;

            Dictionary<string, int> DriversName = new Dictionary<string, int>();

            var drivers = await _context.DriverModel.ToListAsync();
            var names = new List<string>();

            foreach (var driver in drivers)
            {
                names.Add(driver.FirstName + " " + driver.LastName);
            }

            Dictionary<string, int> DriversNamesID = new Dictionary<string, int>();

            foreach (var driver in drivers)
            {
                DriversNamesID.Add(driver.FirstName + " " + driver.LastName, driver.DriverId);
            }

            ViewBag.DriversNamesID = DriversNamesID;


            return View("RaceResult");
        }

        // GET: Race/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (!(HttpContext.Session.GetString("IsLoggedIn") == "true"))
            {
                return RedirectToAction("Account", "Login");
            }
            if (id == null || _context.RaceModel == null)
            {
                return NotFound();
            }

            var raceModel = await _context.RaceModel
                .FirstOrDefaultAsync(m => m.RaceId == id);
            if (raceModel == null)
            {
                return NotFound();
            }

            return View(raceModel);
        }

        // GET: Race/Create
        public IActionResult Create()
        {
            if (!(HttpContext.Session.GetString("IsLoggedIn") == "true"))
            {
                return RedirectToAction("Account", "Login");
            }
            return View();
        }

        // POST: Race/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RaceId,Year,Round,Name,Date,Url")] RaceModel raceModel)
        {
            if (!(HttpContext.Session.GetString("IsLoggedIn") == "true"))
            {
                return RedirectToAction("Account", "Login");
            }
            if (ModelState.IsValid)
            {
                _context.Add(raceModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(raceModel);
        }

        // GET: Race/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (!(HttpContext.Session.GetString("IsLoggedIn") == "true"))
            {
                return RedirectToAction("Account", "Login");
            }
            if (id == null || _context.RaceModel == null)
            {
                return NotFound();
            }

            var raceModel = await _context.RaceModel.FindAsync(id);
            if (raceModel == null)
            {
                return NotFound();
            }
            return View(raceModel);
        }

        // POST: Race/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RaceId,Year,Round,Name,Date,Url")] RaceModel raceModel)
        {
            if (!(HttpContext.Session.GetString("IsLoggedIn") == "true"))
            {
                return RedirectToAction("Account", "Login");
            }
            if (id != raceModel.RaceId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(raceModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RaceModelExists(raceModel.RaceId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(raceModel);
        }

        // GET: Race/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (!(HttpContext.Session.GetString("IsLoggedIn") == "true"))
            {
                return RedirectToAction("Account", "Login");
            }
            if (id == null || _context.RaceModel == null)
            {
                return NotFound();
            }

            var raceModel = await _context.RaceModel
                .FirstOrDefaultAsync(m => m.RaceId == id);
            if (raceModel == null)
            {
                return NotFound();
            }

            return View(raceModel);
        }

        // POST: Race/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (!(HttpContext.Session.GetString("IsLoggedIn") == "true"))
            {
                return RedirectToAction("Account", "Login");
            }
            if (_context.RaceModel == null)
            {
                return Problem("Entity set 'Formula1Context.RaceModel'  is null.");
            }
            var raceModel = await _context.RaceModel.FindAsync(id);
            if (raceModel != null)
            {
                _context.RaceModel.Remove(raceModel);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RaceModelExists(int id)
        {
            return (_context.RaceModel?.Any(e => e.RaceId == id)).GetValueOrDefault();
        }
    }
}

Formula1/Controllers/StandingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Formula1.Data;
using Formula1.Models;


namespace Formula1.Controllers
{
    public class StandingsController : Controller
    {

        private readonly Formula1Context _context;

        public StandingsController(Formula1Context context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            if (!(HttpContext.Session.GetString("IsLoggedIn") == "true"))
            {
                return RedirectToAction("Account", "Login");
            }
            return View();
        }

        public IActionResult TeamsStanding()
        {
            if (!(HttpContext.Session.GetString("IsLoggedIn") == "true"))
            {
                return RedirectToAction("Account", "Login");
            }

            var raceResults = _context.RaceResultsModel.Where(r => r.Position != "NC").ToList();

            Dictionary<TeamModel, int> teamPoints = new Dictionary<TeamModel, int>();
            var teams = _context.TeamModel.ToList();

            foreach (var team in teams)
            {
                teamPoints.Add(team, 0);
            }

            foreach (var raceResult in raceResults)
            {
                var teamId = raceResult.Team.TeamId;
                var team = _context.TeamModel.FirstOrDefault(t => t.TeamId == teamId);
                var points = raceResult.Points;
                teamPoints[team] += points;
            }

            var sortedTeamPoints = teamPoints.OrderByDescending(t => t.Value).ToList();

            ViewBag.TeamPoints = sortedTeamPoints;

            return View();
        }

        public async Task<IActionResult> DriversStanding()
        {
            if (!(HttpContext.Session.GetString("IsLoggedIn") == "true"))
            {
                return RedirectToAction("Account", "Login");
            }

            var raceResults = await _context.RaceResultsModel.Where(r => r.Position != "NC").ToListAsync();

            Dictionary<DriverModel, int> driverPoints = new Dictionary<DriverModel, int>();
            var drivers = await _context.DriverModel.ToListAsync();
            foreach (var driver in drivers)
            {
                driverPoints.Add(driver, 0);
            }

            foreach (var raceResult in raceResults)
            {
                var driverId = raceResult.Driver.DriverId;
                var driver = await _context.DriverModel.FirstOrDefaultAsync(d => d.DriverId == driverId);
                var points = raceResult.Points;
                driverPoints[driver] += points;
                // if (raceResult.SetFastestLap == "Yes")
                // {
                //     driverPoints[driver] += 1;
                // }
            }

            // var sprintResults = await _context.RaceResultsModel.Where(r => r.Sprint == true).ToListAsync();

            // foreach (var sprintResult in sprintResults)
            // {
            //     var driverId = sprintResult.Driver.DriverId;
            //     var driver = await _context.DriverModel.FirstOrDefaultAsync(d => d.DriverId == driverId);
            //     var points = sprintResult.Points;
            //     driverPoints[driver] += points;
            // }

            var sortedDriverPoints = driverPoints.OrderByDescending(d => d.Value).ToList();
            ViewBag.DriverPoints = sortedDriverPoints;

            return View();
        }
    }
}

Formula1/Controllers/TeamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Formula1.Data;
using Formula1.Models;

namespace Formula1.Controllers
{
    public class TeamController : Controller
    {
        private readonly Formula1Context _context;

        public TeamController(Formula1Context context)
        {
            _context = context;
        }

        // GET: Team
        public async Task<IActionResult> Index()
        {
            if (!(HttpContext.Session.GetString("IsLoggedIn") == "true"))
            {
                return RedirectToAction("Account", "Login");
            }
              return _context.TeamModel != null ? 
                          View(await _context.TeamModel.ToListAsync()) :
                          Problem("Entity set 'Formula1Context.TeamModel'  is null.");
        }

        // GET: Team/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (!(HttpContext.Session.GetString("IsLoggedIn") == "true"))
            {
                return RedirectToAction("Account", "Login");
            }
            if (id == null || _context.TeamModel == null)
            {
                return NotFound();
            }

            var teamModel = await _context.TeamModel
                .FirstOrDefaultAsync(m => m.TeamId == id);
            if (teamModel == null)
            {
                return NotFound();
            }

            return View(teamModel);
        }

        // GET: Team/Create
        public IActionResult Create()
        {
            if (!(HttpContext.Session.GetString("IsLoggedIn") == "true"))
            {
                return RedirectToAction("Account", "Login");
            }
            return View();
        }

        // POST: Team/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TeamId,Name,Nationality,Url")] TeamModel teamModel)
        {
            if (!(HttpContext.Session.GetString("IsLoggedIn") == "true"))
            {
                return RedirectToAction("Account", "Login");
            }
            if (ModelState.IsValid)
            {
                _context.Add(teamModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(teamModel);
        }

        // GET: Team/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (!(HttpContext.Session.GetString("IsLoggedIn") == "true"))
            {
                return RedirectToAction("Account", "Login");
            }
            if (id == null || _context.TeamModel == null)
            {
                return NotFound();
            }

            var teamModel = await _context.TeamModel.FindAsync(id);
            if (teamModel == null)
            {
                return NotFound();
            }
            return View(teamModel);
        }

        // POST: Team/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TeamId,Name,Nationality,Url")] TeamModel teamModel)
        {
            if (!(HttpContext.Session.GetString("IsLoggedIn") == "true"))
            {
                return RedirectToAction("Account", "Login");
            }
            if (id != teamModel.TeamId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(teamModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TeamModelExists(teamModel.TeamId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(teamModel);
        }

        // GET: Team/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (!(HttpContext.Session.GetString("IsLoggedIn") == "true"))
            {
                return RedirectToAction("Account", "Login");
            }
            if (id == null || _context.TeamModel == null)
            {
                return NotFound();
            }

            var teamModel = await _context.TeamModel
                .FirstOrDefaultAsync(m => m.TeamId == id);
            if (teamModel == null)
            {
                return NotFound();
            }

            return View(teamModel);
        }

        // POST: Team/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (!(HttpContext.Session.GetString("IsLoggedIn") == "true"))
            {
                return RedirectToAction("Account", "Login");
            }
            if (_context.TeamModel == null)
            {
                return Problem("Entity set 'Formula1Context.TeamModel'  is null.");
            }
            var teamModel = await _context.TeamModel.FindAsync(id);
            if (teamModel != null)
            {
                _context.TeamModel.Remove(teamModel);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TeamModelExists(int id)
        {
          return (_context.TeamModel?.Any(e => e.TeamId == id)).GetValueOrDefault();
        }
    }
}

Formula1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Formula 1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcApplication.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/_Layout.cshtml.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img class="navbar-brand-img" src="~/image/racing-car.png" />

                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @{
                            if (Context.Session.GetString("IsLoggedIn") == "true")
                            {
                                @* <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Account"
                        asp-action="Data">Dane</a>
                        </li> *@
                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Race" asp-action="Index">Races</a>
                                </li>
                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Driver"
                                        asp-action="Index">Drivers</a>
                                </li>
                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Team" asp-action="Index">Teams</a>
                                </li>

                                @* Standings *@
                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Standings"
                                        asp-action="Index">Standings</a>
                                </li>

                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Circuit"
                                        asp-action="Index">Circuits</a>
                                </li>


                                @if (Context.Session.GetString("IsAdmin") == "true")
                                {
                                    <li>
                                        <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                                    </li>
                                }
                            }
                            else
                            {
                                @* <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Account"
                        asp-action="Login">Login</a>
                        </li> *@

                            }
                        }

                    </ul>
                    @if (Context.Session.GetString("IsLoggedIn") == "true")
                    {
                        <form asp-action="Logout" method="post">
                            <div align="center">
                                <button type="submit" class="btn btn-primary">Log out</button>
                            </div>
                        </form>
                    }
                    else
                    {
                        @* <form asp-controller="Login" asp-action="Login">
                    <div align="center">
                    <button type="submit" class="btn btn-primary">Sign in</button>
                    </div>
                    </form> *@
                        <a asp-controller="Account" asp-action="Login" class="btn btn-primary">Sign in</a>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Arkadiusz Paterak, Mateusz Piękoś
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>